#baseurl = "localhost/Pile-of-Thoughts"
baseurl = "https://no-exit.github.io/Pile-of-Thoughts"
title = "Pile of Thoughts"
languageCode = "de-de"
theme = "hello-friend-ng"
paginate = 10

PygmentsCodeFences = true
PygmentsStyle = "monokai"

enableRobotsTXT = true

[author]
  name = "no-exit"

[params]
	dateform = "2. Jan 2006"
	dateformShort = "2. Jan"
	dateformNum = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04"

	subtitle = "Ein Weblog von no-exit"
	# Subtitle for home
	homeSubtitle = "Ein Weblog von no-exit"

	# Set disableReadOtherPosts to true in order to hide the links to other posts.
	disableReadOtherPosts = false

	# Enable sharing buttons, if you like
	enableSharingButtons = false

	readOtherPosts = "Andere Posts lesen"

	[params.logo]
		logoText = "Pile of Thoughts"
		logoHomeLink = "/Pile-of-Thoughts/"
		logoCursorColor = "#FFD866"

	[params.footer]
		# author = true

		topText = []
		bottomText = [
			"Powered by <a href=\"http://gohugo.io\">Hugo</a>",
			"Themed with <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">Hello Friend NG</a>",
			"Hosted on <a href=\"https://github.com/\">GitHub</a>"
		]

[taxonomies]
	category = "blog"
	tag = "tags"
	series = "series"


# And you can even create generic menu
[[menu.main]]
	identifier = "posts"
	name = "Posts"
	url = "posts/"
	weight = 1

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "about"
	weight = 2
